# The application itself is not containerized, as it relies on a non-containerized GUI (e.g., Selenium with a real browser).
# This setup only brings up the PostgreSQL database for local development or integration.
services:
  postgres:
    image: postgres:15
    container_name: postgres-application-aggregator
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application-aggregator
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres-data:

networks:
  application-aggregator:
    driver: bridge
